version: '3'
volumes:
  vendor:
  node_modules:
services:
  app:
    image: node:12.20.1-alpine3.10
    ports:
      - '80:3000'
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm run dev
