name: next build with container
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Installs dependencies
        run: docker-compose run app npm install

      - name: Starts container
        run: docker-compose run export

      - name: Add nojekyll to access _node dir.
        run: touch ./app/out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/out